Repository vietvd13/Training_EMS, pull requests merged in 2021-04, with the labels that each got.

#22 [EMS][CRUD] CRUD Question, Class, Course, User Done
  app/Http/Controllers/Api/ClassController.php
  app/Http/Controllers/Api/CourseController.php
  app/Http/Controllers/Api/QuestionController.php
  app/Http/Controllers/Api/RoleController.php
  app/Http/Controllers/Api/TestController.php
  app/Http/Controllers/Api/UserController.php
  app/Http/Resources/ClassResource.php
  app/Http/Resources/CourseResource.php
  app/Http/Resources/UserResource.php
  app/Models/Classs.php
  app/Models/Question.php
  routes/api.php
Labels: implement

#28 [FE][Manager User] Create Frame Basic Page
  resources/js/lang/en.json
  resources/js/lang/vi.json
  resources/js/views/ManagerUser/index.vue
Labels: implement

#29 [FE][Component] Create component LazyLoad
  resources/js/components/LazyLoad.vue
Labels: implement

#31 [FE][Manager User] Update Message, Validate, Cf
  const/const_value.json
  public/favicon.ico
  resources/js/lang/en.json
  resources/js/lang/vi.json
  resources/js/utils/validate.js
  resources/js/views/ManagerUser/index.vue
Labels: implement

#32 [EMS][Account] Fix Account == password
  app/Http/Controllers/Api/UserController.php
Labels: bug

#33 [FE][Manager User] Update Style Modal Button
  resources/js/style/index.scss
  resources/js/views/ManagerUser/index.vue
Labels: implement

#34 [FE][Manager User] Add disable input email
  resources/js/views/ManagerUser/index.vue
Labels: implement

#36 [EMS][Test] Test CRUD Done
  app/Http/Controllers/Api/TestController.php
  app/Http/Resources/TestResource.php
  app/Models/Course.php
  app/Models/Test.php
  routes/api.php
Labels: implement

#38 [FE][Manager Course] Create view and function Create
  resources/js/api/manage-course.js
  resources/js/lang/en.json
  resources/js/lang/vi.json
  resources/js/style/index.scss
  resources/js/views/ChooseCourse/index.vue
  resources/js/views/ManagerCourse/index.vue
  resources/js/views/ManagerUser/index.vue
Labels: implement

#39 [FE][Manage User and Course] Create UI Course and update User
  resources/js/api/manage-course.js
  resources/js/lang/en.json
  resources/js/lang/vi.json
  resources/js/style/index.scss
  resources/js/views/ManagerCourse/index.vue
  resources/js/views/ManagerUser/index.vue
Labels: implement

#40 [FE][SCSS] Split file and plus point style scss
  resources/js/layout/components/LangSelector/index.vue
  resources/js/layout/components/Navbar/index.vue
  resources/js/style/course.scss
  resources/js/style/index.scss
  resources/js/style/layout.scss
  resources/js/style/user.scss
Labels: implement

#41 [FE][Overall] Create Table Class and fix spelling
  const/const_value.json
  resources/js/lang/en.json
  resources/js/lang/vi.json
  resources/js/router/index.js
  resources/js/views/ManageClass/index.vue
  resources/js/views/ManageCourse/index.vue
  resources/js/views/ManageQuiz/index.vue
  resources/js/views/ManageTest/index.vue
  resources/js/views/ManageUser/index.vue
  resources/js/views/ManagerClass/index.vue
  resources/js/views/TrainerScheduled/index.vue
Labels: implement

#42 [FE][Overall] Create table for all page
  resources/js/lang/en.json
  resources/js/lang/vi.json
  resources/js/views/ManageQuiz/index.vue
  resources/js/views/ManageTest/index.vue
  resources/js/views/TrainerScheduled/index.vue
  resources/js/views/ViewResult/index.vue
Labels: implement

#47 [FE][Manage Class] Create modal and style
  package.json
  resources/js/lang/en.json
  resources/js/lang/vi.json
  resources/js/style/class.scss
  resources/js/style/index.scss
  resources/js/views/ManageClass/index.vue
Labels: implement

#48 [FE][Manage Class] Create Drag Drop table course
  resources/js/api/manage-class.js
  resources/js/views/ManageClass/index.vue
Labels: implement

#49 [EMS][Class API] Update Get List trainee for select
  app/Http/Controllers/Api/UserController.php
  routes/api.php
Labels: implement

#52 [FE][Manage Class] Update modal cf and validation
  resources/js/lang/en.json
  resources/js/lang/vi.json
  resources/js/utils/helperDrag.js
  resources/js/views/ManageClass/index.vue
Labels: bug, implement

#54 [FE][Manage Quiz] Create all Manage Quiz and add some cf
  resources/js/api/manage-quiz.js
  resources/js/lang/en.json
  resources/js/lang/vi.json
  resources/js/style/index.scss
  resources/js/style/quiz.scss
  resources/js/utils/deCode.js
  resources/js/views/ManageClass/index.vue
  resources/js/views/ManageCourse/index.vue
  resources/js/views/ManageQuiz/index.vue
  resources/js/views/ManageUser/index.vue
Labels: implement

#55 [FE][Manage Test] Create UI, Function create test
  resources/js/api/manage-test.js
  resources/js/lang/en.json
  resources/js/lang/vi.json
  resources/js/style/index.scss
  resources/js/style/test.scss
  resources/js/views/ManageTest/index.vue
Labels: implement
